CREATE TABLE `company` (
	`user` INT(11) NOT NULL,
	`amount` INT(11) NOT NULL,
	`date` DATETIME NOT NULL
)

CREATE TABLE `pin_entrance` (
	`user_id` INT(11) NOT NULL,
	`amount` INT(11) NOT NULL,
	`date` DATETIME NOT NULL
)

6551375120 fidelity
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB()
;

CREATE TABLE `countries_supported` (
	`code` INT(11) NOT NULL,
	`name` TEXT NOT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `prestarter`(
	`matrix_id` INT(11) NOT NULL,
	`sponsor` INT(11) NOT NULL,
	`user` INT(11) NOT NULL,
	`lft` INT(11) NOT NULL,
	`rgt` INT(11) NOT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `driver_tree` (
	`matrix_id` INT(11) UNIQUE, PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`sponsor` INT(11) NOT NULL,
	`user` INT(11) NOT NULL,
	`a` INT(11) NULL DEFAULT NULL,
	`b` INT(11) NULL DEFAULT NULL,
	`c` INT(11) NULL DEFAULT NULL,
	`d` INT(11) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `earnings` (
	`user_id` INT(11) NOT NULL,
	`feeder` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`stage1` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`stage2` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`stage3` INT(11) UNSIGNED ZEROFILL NOT NULL,
		`stage4` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`powerbank` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`phone` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`laptop` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`leadership` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`empower` INT(11) UNSIGNED ZEROFILL NOT NULL,
	`salary` INT(11) UNSIGNED ZEROFILL NOT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `jumper_tree` (
	`sponsor_id` INT(11) NOT NULL,
	`a` INT(11) NULL DEFAULT NULL,
	`b` INT(11) NULL DEFAULT NULL,
	`c` INT(11) NULL DEFAULT NULL,
	`aa` INT(11) NULL DEFAULT NULL,
	`ab` INT(11) NULL DEFAULT NULL,
	`ac` INT(11) NULL DEFAULT NULL,
	`ba` INT(11) NULL DEFAULT NULL,
	`bb` INT(11) NULL DEFAULT NULL,
	`bc` INT(11) NULL DEFAULT NULL,
	`ca` INT(11) NULL DEFAULT NULL,
	`cb` INT(11) NULL DEFAULT NULL,
	`cc` INT(11) NULL DEFAULT NULL,
	`aaa` INT(11) NULL DEFAULT NULL,
	`aab` INT(11) NULL DEFAULT NULL,
	`aac` INT(11) NULL DEFAULT NULL,
	`aba` INT(11) NULL DEFAULT NULL,
	`abb` INT(11) NULL DEFAULT NULL,
	`abc` INT(11) NULL DEFAULT NULL,
	`aca` INT(11) NULL DEFAULT NULL,
	`acc` INT(11) NULL DEFAULT NULL,
	`acb` INT(11) NULL DEFAULT NULL,
	`baa` INT(11) NULL DEFAULT NULL,
	`bab` INT(11) NULL DEFAULT NULL,
	`bac` INT(11) NULL DEFAULT NULL,
	`bba` INT(11) NULL DEFAULT NULL,
	`bbb` INT(11) NULL DEFAULT NULL,
	`bbc` INT(11) NULL DEFAULT NULL,
	`bca` INT(11) NULL DEFAULT NULL,
	`bcb` INT(11) NULL DEFAULT NULL,
	`bcc` INT(11) NULL DEFAULT NULL,
	`caa` INT(11) NULL DEFAULT NULL,
	`cab` INT(11) NULL DEFAULT NULL,
	`cac` INT(11) NULL DEFAULT NULL,
	`cba` INT(11) NULL DEFAULT NULL,
	`cbb` INT(11) NULL DEFAULT NULL,
	`cbc` INT(11) NULL DEFAULT NULL,
	`cca` INT(11) NULL DEFAULT NULL,
	`ccb` INT(11) NULL DEFAULT NULL,
	`ccc` INT(11) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `matix_sum` (
	`starter` INT(11) NULL DEFAULT NULL,
	`jumper` INT(11) NULL DEFAULT NULL,
	`runner` INT(11) NULL DEFAULT NULL,
	`pilot` INT(11) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `matrix_count` (
	`user` INT(11) NOT NULL,
	`amount` INT(11) NOT NULL,
	`date` DATETIME NOT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `pilot_tree` (
	`sponsor_id` INT(11) NOT NULL,
	`a` INT(11) NULL DEFAULT NULL,
	`b` INT(11) NULL DEFAULT NULL,
	`c` INT(11) NULL DEFAULT NULL,
	`aa` INT(11) NULL DEFAULT NULL,
	`ab` INT(11) NULL DEFAULT NULL,
	`ac` INT(11) NULL DEFAULT NULL,
	`ba` INT(11) NULL DEFAULT NULL,
	`bb` INT(11) NULL DEFAULT NULL,
	`bc` INT(11) NULL DEFAULT NULL,
	`ca` INT(11) NULL DEFAULT NULL,
	`cb` INT(11) NULL DEFAULT NULL,
	`cc` INT(11) NULL DEFAULT NULL,
	`aaa` INT(11) NULL DEFAULT NULL,
	`aab` INT(11) NULL DEFAULT NULL,
	`aac` INT(11) NULL DEFAULT NULL,
	`aba` INT(11) NULL DEFAULT NULL,
	`abb` INT(11) NULL DEFAULT NULL,
	`abc` INT(11) NULL DEFAULT NULL,
	`aca` INT(11) NULL DEFAULT NULL,
	`acc` INT(11) NULL DEFAULT NULL,
	`acb` INT(11) NULL DEFAULT NULL,
	`baa` INT(11) NULL DEFAULT NULL,
	`bab` INT(11) NULL DEFAULT NULL,
	`bac` INT(11) NULL DEFAULT NULL,
	`bba` INT(11) NULL DEFAULT NULL,
	`bbb` INT(11) NULL DEFAULT NULL,
	`bbc` INT(11) NULL DEFAULT NULL,
	`bca` INT(11) NULL DEFAULT NULL,
	`bcb` INT(11) NULL DEFAULT NULL,
	`bcc` INT(11) NULL DEFAULT NULL,
	`caa` INT(11) NULL DEFAULT NULL,
	`cab` INT(11) NULL DEFAULT NULL,
	`cac` INT(11) NULL DEFAULT NULL,
	`cba` INT(11) NULL DEFAULT NULL,
	`cbb` INT(11) NULL DEFAULT NULL,
	`cbc` INT(11) NULL DEFAULT NULL,
	`cca` INT(11) NULL DEFAULT NULL,
	`ccb` INT(11) NULL DEFAULT NULL,
	`ccc` INT(11) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `pin` (
	`pin` TEXT NOT NULL,
	`serial` TEXT NULL DEFAULT NULL,
	`user_id` INT(11) NULL DEFAULT NULL,
	`date_created` TIMESTAMP NOT NULL DEFAULT '',
	`date_used` TIMESTAMP NULL DEFAULT ''
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `pre_starter` (
	`sponsor` INT(11) NOT NULL,
	`user` INT(11) NOT NULL,
	`a` INT(11) NOT NULL,
	`b` INT(11) NOT NULL,
	`c` INT(11) NOT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `profile` (
	`user_id` INT(11) NOT NULL,
	`bank` TEXT NOT NULL,
	`account_name` TEXT NOT NULL,
	`account_number` INT(11) NOT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `runner_tree` (
	`sponsor_id` INT(11) NOT NULL,
	`a` INT(11) NULL DEFAULT NULL,
	`b` INT(11) NULL DEFAULT NULL,
	`c` INT(11) NULL DEFAULT NULL,
	`aa` INT(11) NULL DEFAULT NULL,
	`ab` INT(11) NULL DEFAULT NULL,
	`ac` INT(11) NULL DEFAULT NULL,
	`ba` INT(11) NULL DEFAULT NULL,
	`bb` INT(11) NULL DEFAULT NULL,
	`bc` INT(11) NULL DEFAULT NULL,
	`ca` INT(11) NULL DEFAULT NULL,
	`cb` INT(11) NULL DEFAULT NULL,
	`cc` INT(11) NULL DEFAULT NULL,
	`aaa` INT(11) NULL DEFAULT NULL,
	`aab` INT(11) NULL DEFAULT NULL,
	`aac` INT(11) NULL DEFAULT NULL,
	`aba` INT(11) NULL DEFAULT NULL,
	`abb` INT(11) NULL DEFAULT NULL,
	`abc` INT(11) NULL DEFAULT NULL,
	`aca` INT(11) NULL DEFAULT NULL,
	`acc` INT(11) NULL DEFAULT NULL,
	`acb` INT(11) NULL DEFAULT NULL,
	`baa` INT(11) NULL DEFAULT NULL,
	`bab` INT(11) NULL DEFAULT NULL,
	`bac` INT(11) NULL DEFAULT NULL,
	`bba` INT(11) NULL DEFAULT NULL,
	`bbb` INT(11) NULL DEFAULT NULL,
	`bbc` INT(11) NULL DEFAULT NULL,
	`bca` INT(11) NULL DEFAULT NULL,
	`bcb` INT(11) NULL DEFAULT NULL,
	`bcc` INT(11) NULL DEFAULT NULL,
	`caa` INT(11) NULL DEFAULT NULL,
	`cab` INT(11) NULL DEFAULT NULL,
	`cac` INT(11) NULL DEFAULT NULL,
	`cba` INT(11) NULL DEFAULT NULL,
	`cbb` INT(11) NULL DEFAULT NULL,
	`cbc` INT(11) NULL DEFAULT NULL,
	`cca` INT(11) NULL DEFAULT NULL,
	`ccb` INT(11) NULL DEFAULT NULL,
	`ccc` INT(11) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `sessions` (
	`session_id` VARCHAR(128) NOT NULL COLLATE 'utf8mb4_bin',
	`expires` INT(11) UNSIGNED NOT NULL,
	`data` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`session_id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `starter_tree` (
	`sponsor` INT(11) NOT NULL,
	`user` INT(11) NOT NULL,
	`a` INT(11) NULL DEFAULT NULL,
	`b` INT(11) NULL DEFAULT NULL,
	`c` INT(11) NULL DEFAULT NULL,
	`aa` INT(11) NULL DEFAULT NULL,
	`ab` INT(11) NULL DEFAULT NULL,
	`ac` INT(11) NULL DEFAULT NULL,
	`ba` INT(11) NULL DEFAULT NULL,
	`bb` INT(11) NULL DEFAULT NULL,
	`bc` INT(11) NULL DEFAULT NULL,
	`ca` INT(11) NULL DEFAULT NULL,
	`cb` INT(11) NULL DEFAULT NULL,
	`cc` INT(11) NULL DEFAULT NULL,
	`aaa` INT(11) NULL DEFAULT NULL,
	`aab` INT(11) NULL DEFAULT NULL,
	`aac` INT(11) NULL DEFAULT NULL,
	`aba` INT(11) NULL DEFAULT NULL,
	`abb` INT(11) NULL DEFAULT NULL,
	`abc` INT(11) NULL DEFAULT NULL,
	`aca` INT(11) NULL DEFAULT NULL,
	`acc` INT(11) NULL DEFAULT NULL,
	`acb` INT(11) NULL DEFAULT NULL,
	`baa` INT(11) NULL DEFAULT NULL,
	`bab` INT(11) NULL DEFAULT NULL,
	`bac` INT(11) NULL DEFAULT NULL,
	`bba` INT(11) NULL DEFAULT NULL,
	`bbb` INT(11) NULL DEFAULT NULL,
	`bbc` INT(11) NULL DEFAULT NULL,
	`bca` INT(11) NULL DEFAULT NULL,
	`bcb` INT(11) NULL DEFAULT NULL,
	`bcc` INT(11) NULL DEFAULT NULL,
	`caa` INT(11) NULL DEFAULT NULL,
	`cab` INT(11) NULL DEFAULT NULL,
	`cac` INT(11) NULL DEFAULT NULL,
	`cba` INT(11) NULL DEFAULT NULL,
	`cbb` INT(11) NULL DEFAULT NULL,
	`cbc` INT(11) NULL DEFAULT NULL,
	`cca` INT(11) NULL DEFAULT NULL,
	`ccb` INT(11) NULL DEFAULT NULL,
	`ccc` INT(11) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `user` (
	`user_id` INT(11) NOT NULL AUTO_INCREMENT,
	`full_name` VARCHAR(50) NOT NULL DEFAULT '0',
	`username` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`code` INT(11) NOT NULL,
	`phone` BIGINT(20) NOT NULL,
	`password` TEXT NOT NULL,
	`status` INT(11) NOT NULL DEFAULT '0',
	`sponsor` TEXT NULL DEFAULT NULL,
	`verification` TEXT NOT NULL DEFAULT 'No',
	`paid` TEXT NOT NULL DEFAULT 'No',
	`date_joined` DATETIME NOT NULL DEFAULT '',
	PRIMARY KEY (`user_id`),
	UNIQUE INDEX `username` (`username`),
	UNIQUE INDEX `email` (`email`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=23
;